backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img
site_url: https://p2p.hackclub.com
# logo_url: https://your-site.com/images/logo.svg (https://www.netlifycms.org/docs/configuration-options/#custom-logo)

collections:
  - name: "missions"
    label: "Missions"
    folder: "content/missions"
    create: true
    slug: "{{slug}}"
    editor:
     preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "URL Path", name: "slug", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
